# Dataset Related
# num_points: 1024  # number of poins actually used in training and evaluation
num_points: 2048
# num_points: 2900  # Default value for MS1MV2-3D reconstructed by MICA
dataset:
  common:
    NAME: MS1MV2_3D
    data_dir: '/home/bjgbiesseck/GitHub/BOVIFOCR_MICA_3Dreconstruction/demo/output/MS-Celeb-1M_3D_reconstruction_originalMICA/ms1m-retinaface-t1/images'
  train:
    split: train
    # num_points: 1024  # in training, use sampled 1024 points for data augmentation.
    num_points: 2048
    # num_points: 2900  # Default value for MS1MV2-3D reconstructed by MICA
  val:
    split: test
    # num_points: 1024  # in testing, use uniformly pre-sampled 1024 points for evaluation (following https://github.com/lulutang0608/Point-BERT)
    num_points: 2048
    # num_points: 2900  # Default value for MS1MV2-3D reconstructed by MICA

feature_keys: pos

datatransforms:
  train: [PointsToTensor, PointCloudScaleAndTranslate]  # rotation does not help
  vote: [PointCloudScaleAndTranslate]
  val: [PointsToTensor]
  kwargs:
    shift: [0.2, 0.2, 0.2]
# batch_size: 32     # original
# batch_size: 64
batch_size: 128
# batch_size: 16
# batch_size: 8
dataloader:
  num_workers: 6

num_classes: 1000
# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #
# training receipe borrowed from: https://github.com/yanx27/Pointnet_Pointnet2_pytorch

# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #
# this one is better. 
sched: cosine
# epochs: 100
epochs: 50
warmup_epochs: 0
min_lr: null

# Training parameters
lr: 0.001
# lr: 0.0005
optimizer:
 # NAME: 'adamw'   # original
 NAME: 'sgd'
 weight_decay: 0.05

grad_norm_clip: 1

criterion_args:   # args passed to openpoints/loss/build.py -> ArcFace.__init__()
  NAME: ArcFace   # for face recognition
  margin: 0.5
  scale: 32
  # scale: 16
  num_classes: 0   # value set in file 'openpoints/dataset/ms1mv2_3d/ms1mv2_3d_loader.py'

# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
log_dir: 'ms1mv2_3d'
print_freq: 10
val_freq: 1

# ----------------- Model related
# val_batch_size: 64     # original
val_batch_size: 128
# val_batch_size: 32
# val_batch_size: 16
pretrained_path: null

wandb:
  project: PointNeXt-MS1MV2-3D

seed: null
